### PR TITLE
support precision time in UTC

### PR DESCRIPTION
**Pull request by truongsinh**
Current Gopro firmware does not support timezone nor DST, and setting your Gopro to UTC time [will fix](https://community.gopro.com/t5/Cameras/Time-zone-set-incorrectly/td-p/265136) time problem with any Photo/Video manager, including Google Photo.

While waiting for this to be merge, this feature is available at https://truongsinh.github.io/gopro-labs/control/precisiontime-utc/ (it also has support for offline access)

### CODE REVIEW

**Comment by volition74** [comment]
Yes yes can we have this fixed? please. Been an issue since the first GoPro I am led to believe. 

Requests on forums I've posted over time.

[https://community.gopro.com/t5/GoPro-Labs/Super-important-Metadata-needs-to-store-local-Timezone-for-GP/m-p/627482](url)

[https://community.gopro.com/t5/Cameras/incorrect-timezone-issue-persists-3-years-plus-and-date-on/m-p/570955#/M139301](url)

**Comment by truongsinh** [comment]
@volition74 meanwhile, use mine fork at https://truongsinh.github.io/gopro-labs/control/precisiontime-utc/ (it also has support for offline access)

**Comment by jacekmusial** [comment]
@truongsinh  I would recommend adding add these people in the Reviewers field: `lbrownell-gpsw` and `dnewman-gpsw`

**Comment by truongsinh** [comment]
> @truongsinh I would recommend adding add these people in the Reviewers field: `lbrownell-gpsw` and `dnewman-gpsw`

I'm pretty much sure I can't change any field (reviewers, assignees, labels, etc). @lbrownell-gpsw and @dnewman-gpsw can you take a look?

**Comment by dnewman-gpsw** [comment]
Sorry I missed this for so long.  It is a good idea, so it is now implemented.

**Pull request closed without merging**
